import utils


def find_ori(file, txt=''):
    if file:
        dna = ''.join(f.strip() for f in open(file).readlines())
        # utils.plot_skew(dna)
        min_skew = utils.get_min_skew_posiion(dna)[0]
        print(min_skew)
        L = 500
        dna_box = dna[min_skew-L:min_skew+L]
    else:
        dna_box = txt
    k = 9
    d = 1
    most_freq_kmer = utils.frequent_kmers(dna_box, k, d , True)
    print('Found ORI', most_freq_kmer)



def get_profile(string):
    base_lines = string.split('\n')
    bases = [[float(s) for s in line.split()] for line in base_lines]
    prof = [{} for _ in range(len(bases[0]))]
    for i in range(len(prof)):
        prof[i]['A'] = bases[0][i]
        prof[i]['C'] = bases[1][i]
        prof[i]['G'] = bases[2][i]
        prof[i]['T'] = bases[3][i]
    print(prof)
    return prof


if __name__ == "__main__":
    str = """0.268 0.254 0.254 0.338 0.352 0.31 0.239 0.211 0.268 0.268 0.296 0.141 0.31 0.197
0.225 0.296 0.225 0.197 0.239 0.268 0.282 0.338 0.296 0.225 0.211 0.268 0.254 0.31
0.296 0.183 0.296 0.225 0.211 0.225 0.225 0.254 0.239 0.268 0.296 0.268 0.239 0.254
0.211 0.268 0.225 0.239 0.197 0.197 0.254 0.197 0.197 0.239 0.197 0.324 0.197 0.239
"""
    profile = get_profile(str)
    dna = 'TCCAACTCGAGGAATTTAGGAATCGTGACCGTAGGTGCGTGAATGTAAGAGCTAGGAGTAGGGTCTCCTATCAGGGCTTCAACCACCCCACACGTGAAAGCAAACGATTGCTCTAATCCATCCCCCCGTGATTCTGTTGTCGTAATAGCCACGAGGTGCTGCGCGATCATTGAGCTACGACCTTGATGGGCCGGTCGACGTGGGGCGGTTCAGTTACTACTATTGTTGGTACTTTTATCTTTGCACCGGACATCATCCCTGAGCGATACGCGGTCTCACGCGAACTCCATAGGCTTGAAGCACCTCCCAGAAACGGCACAGCCCTCGCCGAAGACCATATTGTATCGTAGTTCCGCGTGATGAGTACATGGATTTATTCTTATTTTCTACGGCCCTAAACGGGCACCGCTAGGGTGTCGCGACGTCTGAGATAGGGCAGTGAAGCTACCCGCTAGCCTAAGGTCCGACCAGGGGTGCAATTTTTCGCGAAGCGACAATAATCAACGTTTTCATGCACCCCGAACTCAAGGATGTCCACGGAATTCTGTAGGAGGTACGTGCGCACATTATGCAACAGCTGCGTAACACCCCGGTCCGCGTCTATCACGCTAACTTTAGAAAGTCGGGCAACCACTGGTGTAAACCTTGCGACTCCCTTTCCATTGACTTCCACAGTCCAGGAATCTTGTCAGACGGCTGACCTCAGAATTCAAGAACAAAAAGCTACCGTCTTAAATGGTATTCGTTACCGGCCCTACGTAATAGCTACAGGCGGCCCAAATGCTACTGATCTCTAATTCAAGTTACGAGCTTATAGATGGCGCCCCCTAAGAGGACGGACCGCTGTATAAAAATTCACTGTCAAAGGATAATCTTCAAAATTCGGGATTAAACCGTGGAGCCGCGTTCGACGATACAAGGAACTCAGCACGGTAGTCTCACCGGGGTGTTCTTACCGATCCCTCAACGCGGAAACACTGATAGGAGCATCCATCGTGAT'
    print(utils.most_probable_kmer_from_profile(profile, dna))

    exit()

    find_ori('data\\Salmonella_enterica.txt')
    find_ori('data\\E_coli.txt')

